export const ENDPOINTS = {
  USER_AUTH_SEND_OTP: '/v1/user/auth/send-otp',
  USER_AUTH_VERIFY_OTP: '/v1/user/auth/verify-otp',
  USER_PROFILE_UPDATE: '/v1/user/profile/update',
  USER_ADDRESSES: '/v1/user/addresses',
  USER_ADDRESS_STORE: '/v1/user/addresses/store',
  userAddressUpdate: (id: number) => `/v1/user/addresses/${id}/update`,
  userAddressDelete: (id: number) => `/v1/user/addresses/${id}/delete`,
  userAddressDefault: (id: number) => `/v1/user/addresses/${id}/default`,
  USER_STORES_NEARBY: '/v1/user/stores/nearby',
  USER_STORE_CATALOG: '/v1/user/stores/catalog',
  USER_STORE_PRODUCTS: '/v1/user/stores/products',
  USER_HOME_CATEGORIES: '/v1/user/home/categories',
  USER_CATEGORY_PRODUCTS: '/v1/user/categories/products',
} as const;
