export const ENDPOINTS = {
  USER_AUTH_SEND_OTP: '/v1/user/auth/send-otp',
  USER_AUTH_VERIFY_OTP: '/v1/user/auth/verify-otp',
  USER_SESSION: '/v1/user/session',
  USER_PROFILE_UPDATE: '/v1/user/profile/update',
  USER_ADDRESSES: '/v1/user/addresses',
  USER_ADDRESS_STORE: '/v1/user/addresses/store',
  userAddressUpdate: (id: number) => `/v1/user/addresses/${id}/update`,
  userAddressDelete: (id: number) => `/v1/user/addresses/${id}/delete`,
  userAddressDefault: (id: number) => `/v1/user/addresses/${id}/default`,
  USER_STORES_NEARBY: '/v1/user/stores/nearby',
  USER_STORE_CATALOG: '/v1/user/stores/catalog',
  USER_STORE_PRODUCTS: '/v1/user/stores/products',
  USER_HOME_CATEGORIES: '/v1/user/home/categories',
  USER_CATEGORY_PRODUCTS: '/v1/user/categories/products',
  USER_PRODUCT_DETAIL: '/v1/user/products/detail',
  USER_CART: '/v1/user/cart',
  USER_CART_ADD: '/v1/user/cart/add',
  USER_CART_UPDATE: '/v1/user/cart/update',
  USER_ORDER_PLACE: '/v1/user/orders/place',
  USER_ORDER_SHOW: '/v1/user/orders/show',
} as const;
